// Chapter/event settings. The JSON is generated by scripts/prepare.py from
// chapter.config.yaml + content/ - edit those, never this. If the import
// below fails, run `python3 scripts/prepare.py` from the repo root first.
import chapter from './chapter.generated.json'

export default chapter

export function phoneHref(phone) {
  return phone ? `tel:${phone.replace(/[^\d+]/g, '')}` : ''
}
